### ISSUE TITLE
Timing of cropTo promise resolution with media capture-transform

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-region#12]
cropTo is resolving a promise at which point cropping is supposed to be applied.
It seems that we could try to tighten the timing of the promise resolution with the media capture transform.
Ideally, when the promise resolves, the media capture transform would not have missed any cropped frame, and the cropped frame could be retrieved by calling enough of read() calls that would resolve in the same event loop.

**Comment by eladalon1983** [comment]
Could you please clarify? Are you voicing a concern that, without some refinement of the spec, it would not be possible to guarantee that transforms have time to operate on the first frame?

If so, please suggest the edit. But my initial reaction is that it might be non-trivial to implement such a guarantee, so we'd better leave this as a possible future improvement, lest the spec ends up promising more than implementations end up delivering.

**Comment by youennf** [comment]
> Are you voicing a concern that, without some refinement of the spec, it would not be possible to guarantee that transforms have time to operate on the first frame?

Yes, I think it should be possible to use cropTo promise resolution as a signal that the first newly cropped frame was enqueued in the media capture transform ReadableStream.
This is similar to what we are doing for generateKeyFrame in webrtc encoded transform: if the promise resolves, it means a key frame was just enqueued in the readable stream within the current event loop.

I think a general note stating the intent in the spec would be good enough for now.

**Comment by eladalon1983** [comment]
> I think a general note stating the intent in the spec would be good enough for now.

If you could send a PR, I'd be glad to review it.
