### ISSUE TITLE
cropTo is returning promises but it is unclear when promises are supposed to be rejected synchronously or not

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-region#14]
For promise-based operations, we usually use language like:
1. check if state1 is ok, if not return a rejected promise // synchronously rejected promise.
2. check if state2 is ok, if not return a rejected promise // synchronously rejected promise.
3. Create a promise
4. Run the following steps in parallel: //asynchronously settled promise.
5. return promise.

It seems like the self-capture track check step can be made synchronously.
It seems the MUST validate cropTarget step should be done asynchronously, as part of a 'run steps in parallel' section.

Also the current algorithm seems to check for valid crop target twice (step 2 and step 4.2). Probably step 4.2 valid CropTarget is unneeded? Or could it be that a crop target is valid in step 2 but invalid in step 4.2.

**Comment by eladalon1983** [comment]
Step 2 validates the track.
Step 4.2 validates the token.

The validation of the token is asynchronous. There are multiple reasons, but the simplest one is that if the token originates from a cross-origin iframe (which is also out-of-process), that iframe could be navigated, leading to all of its tokens becoming invalidated. To validate the token's validity, communication with another process is necessary, be it a central coordinating process (Chrome's current implementation) or the iframe's process (theoretically speaking).

**Comment by youennf** [comment]
Right, I think there is consensus here so this could be marked as editorial.
As I said in the initial message, having some step-by-step algorithm and making use of 'run steps in parallel' would help implementors to have it right, as well as WPT tests of course.

**Comment by eladalon1983** [comment]
PRs welcome. :-)
