### ISSUE TITLE
Decisions concerning clones 

### ISSUE THREAD

**Issue by eladalon1983** [w3c/mediacapture-region#2]
Implementation-wise, at least two browsers (Chrome and Edge) would find it difficult to allow the original track and a cloned track[1] to be cropped to different targets. Would the following two changes to the spec be acceptable?
1. Trying to `clone()` a "cropped" track raises an exception.
2. Trying to invoke `cropTo()` on either (i) an original track which was cloned or (ii) one of its clones, raises an exception.

Thoughts, @youennf, @jan-ivar and @alvestrand?

--
[1] Or two different clones.

**Comment by youennf** [comment]
If cropping to different targets is difficult, it probably means that an API at MediaStreamTrack is not a great place.
Instead, we could well have another object that would be able to manipulate the source of a track and all its clones.
Such object could well be either CaptureHandle or an object that would be returned from the getDisplayMedia call (say given by the event discussed in https://github.com/w3c/mediacapture-screen-share/issues/190).

**Comment by eladalon1983** [comment]
Ultimately, I do think we can (and should) support cropping clones to different targets. It's challenging to implement on Chromium-based browsers, but not impossible. The benefits to apps/users are there, so ideally we would eventually support this. I therefore still think it's best to expose the API on MST, and to employ spec language that allows a user agent to reject cloning+cropping if the UA does not yet support that, with the intention that all UAs would eventually implement support for this.

**Comment by eladalon1983** [comment]
This is my own issue, and it's not seen any activity in 4 months. I believe it's safe to close.
