### ISSUE TITLE
CropTarget and cropTo algorithms should be based on existing HTML/CSS definitions

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-region#20]
The spec is stating:
```The user agent MUST start cropping [this](https://webidl.spec.whatwg.org/#this) video track to the contours of the element referenced by this [CropTarget](https://w3c.github.io/mediacapture-region/#dom-croptarget).```

The contours of the element is not a well defined term. We should be able to reference either CSS or HTML spec to provide a more precise definition. One possibility would be to refer to https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect.
Or refer to https://drafts.csswg.org/cssom-view/#layout-box.
Something like:
```The user agent MUST start cropping [this](https://webidl.spec.whatwg.org/#this) video track to the [layout box](...) of the element referenced by this [CropTarget](https://w3c.github.io/mediacapture-region/#dom-croptarget).```

**Comment by eladalon1983** [comment]
The `fpwd-non-blocking` label means that we need to document pending consensus, but not reach consensus on this, in order to reach FPWD.

**Comment by eladalon1983** [comment]
(Removed these labels because I'd either have to apply them throughout, which would be tedious, or only apply them where it seemed non-trivial that these were non-blocking, which would still give the impression that everything else *is* blocking.)
