### ISSUE TITLE
CropTarget should be made serializable

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-region#21]
One main use case is for a cross origin iframe to pass a CropTarget through postMessage.
This requires CropTarget to be either Transferable or Serializable.
I would tend to go with Serializable.

**Comment by eladalon1983** [comment]
+1 for making it Serializable.

**Comment by eladalon1983** [comment]
@jan-ivar, any objections?

**Comment by jan-ivar** [comment]
SGTM
