### ISSUE TITLE
CropTarget should probably be exposed to worker

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-region#25]
CropTarget should probable be exposed to worker

**Comment by eladalon1983** [comment]
`CropTarget`s cannot be constructed directly using `new`. Is it necessary to expose them to window/worker at all?

**Comment by youennf** [comment]
Tracks are now exposed in workers (https://w3c.github.io/mediacapture-extensions/#transferable-mediastreamtrack).
cropTo is thus defined (and useful) in workers.
Given CropTarget is being made serializable, it is made available to workers as well.
Given all of this, it makes sense to expose CropTarget in both environments.

**Comment by eladalon1983** [comment]
Please re-examine the question I am raising. Effectively, it's about what "exposing" means:
* If it means "allows using `new` to produce such an object in the exposed context" - then we don't need to expose in either Window **or** Worker.
* If it means "allows objects of a given type to exist in the exposed context" - then we do indeed need to expose in both Window and Worker.

Depending on what expose means, let's do the right thing.
Do you happen to know specifically what expose means?

**Comment by youennf** [comment]
Using new would mean adding a constructor, WebIDL has specific keywords for that.
What exposes means is whether to expose the CropTarget interface as a property of the global scope: Window, DedicatedWorkerGlobalScope...
I believe we need that.

**Comment by eladalon1983** [comment]
> Using new would mean adding a constructor, WebIDL has specific keywords for that. What exposes means is whether to expose the CropTarget interface as a property of the global scope: Window, DedicatedWorkerGlobalScope... I believe we need that.

For my education - what would happen if we try to postMessage a transferable object to a context in which it is not exposed?
