### ISSUE TITLE
Spec erroneously limits self-capture to same-document/iframe

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-region#40]
There's some [evidence](https://github.com/w3c/mediacapture-region/issues/17#issuecomment-1029472223) this spec is confusing browsing context with top-level browsing context throughout. As a result, the spec's limiting of cropping to elements in the same document that is calling cropTo, appears erroneous:
* In [§ 4. Scope](https://w3c.github.io/mediacapture-region/#scope): _"As presently defined, [cropTo](https://w3c.github.io/mediacapture-region/#dom-browsercapturemediastreamtrack-cropto)(ID) returns a [rejected](https://webidl.spec.whatwg.org/#reject) [Promise](https://webidl.spec.whatwg.org/#idl-promise) if the ID is not associated with an [Element](https://dom.spec.whatwg.org/#element) within the current [browsing context](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context)."_

The "current browsing context" of a cropTo() call from an iframe is the browsing context local to that iframe only. In contrast, most of the hard discussions I've taken part in in this repo have been around cross-origin serialization of cropTarget, which implies this is not the case. I therefore think fixing this is mostly editorial.

**Comment by eladalon1983** [comment]
Indeed, the intention was "top level browsing context or any of its descendant browsing contexts."
