### ISSUE TITLE
Should cropTo(undefined) reject if track not cropped?

### ISSUE THREAD

**Issue by eladalon1983** [w3c/mediacapture-region#60]
Consider this code:
```js
const stream = await navigator.mediaDevices.getDisplayMedia(); 
const [track] = stream.getVideoTracks();
track.cropTo(undefined);
```
The track was never cropped, yet the app asks for it to be uncropped. What should happen now?

The spec says:
> If [this](https://webidl.spec.whatwg.org/#this) track is [uncropped](https://w3c.github.io/mediacapture-region/#dfn-uncropped), the user agent MUST only accept [valid CropTargets](https://w3c.github.io/mediacapture-region/#dfn-valid-croptarget).

Looking at it again, this seems to me counterproductive. Consider an application that has shuffled the track around some layers. Maybe the new layer does not wish to poll other layers for state, and just wants to ensure the track is not cropped by calling `cropTo(undefined)`. It seems to me more developer-friendly to allow this.

**Comment by youennf** [comment]
It makes sense to me to not reject. Also, maybe there should be a CropTarget getter since cropTo is nothing but an asynchrony setter.

**Comment by eladalon1983** [comment]
> It makes sense to me to not reject.

Great. I'll send a PR.

> Also, maybe there should be a CropTarget getter since cropTo is nothing but an asynchrony setter.

I really want to just say "yes" and build forward momentum, but I think we could start a separate discussion for this. It's not necessarily as simple as it initially sounds. See here:
```js
const stream = await getDisplayMedia();
const [track] = stream.getVideoTracks();
console.log(`${track.getCropTarget()}`);  // Presumably prints `undefined`?
track.cropTo(t1);  // Note lack of `await`.
track.cropTo(t2);  // Note lack of `await`.  
console.log(`${track.getCropTarget()}`);  // Unclear what's printed...? undefined? t1? t2?
```
