### ISSUE TITLE
Behavior when full screened

### ISSUE THREAD

**Issue by TomiS** [w3c/mediacapture-region#81]
Trying to use the media capture in a presentation tool type use case where I open a secondary window with `window.open` into which I send the video stream. For the tool to work properly, I also need to full screen the secondary window, but that is not working great because the "Sharing [address] (Stop sharing)" banner is now visible also when the view is in full screen mode (at least in Chorome). I understand the security concerns, but this makes the whole feature quite unusable, imho. In general, the banner takes huge amount of screen estate given it's also visible on every other tab. It needs to be toned down _a lot_. I'm not sure if this is strictly about the region API, but it's highly related, so posting this here at least for now.

Otherwise great job, and this is indeed an interesting new API/feature with lots of potential. Thanks!

**Comment by eladalon1983** [comment]
> I'm not sure if this is strictly about the region API

I don't think it's about the Region Capture API at all.
The Chromium bug tracker is over at https://issues.chromium.org/issues. (FYI though that if you file an issue there, it's likely that it'll end up on my desk, and atm, I don't think it'll be actionable.)

**Comment by TomiS** [comment]
Thanks for the answer and sorry about posting to a wrong repo. I understand issues like these might be hard to solve, but I just wanted to mention about this in case it ever comes up in discussions with relevant people. Sometimes seemingly unrelated features/behaviors can practically break other features.

Closing.
