### ISSUE TITLE
is this still an experimental feature?

### ISSUE THREAD

**Issue by spxneo** [w3c/mediacapture-region#82]
when will it be available in chrome/firefox browsers?

is it now possible to capture iframe window and the user's interactions with the content and stream it via webrtc ?

thank you so much for implementing this I've been trying all sorts of weird hacky stuff, this API appears to suit my needs.

**Comment by eladalon1983** [comment]
> when will it be available in chrome/firefox browsers?

It shipped in Chrome roughly one year ago. (See [here](https://chromestatus.com/feature/5712447794053120).)
I don't know what other browsers plans are.

> is it now possible to capture iframe window and the user's interactions with the content and stream it via webrtc ?

It is. You could check out how Google Docs + Google Meet do it. Look for the camera-like icon on the top-right corner in Docs, right next to the "share" button.

> thank you so much for implementing this I've been trying all sorts of weird hacky stuff, this API appears to suit my needs.

That's great to hear.
You'd might like to know that while this API *has* shipped in Chrome, we are experimenting with an even superior alternative called Element Capture. See [here](https://developer.chrome.com/docs/web-platform/element-capture) for details. If that helps you too, please make sure to leave feedback [here](https://github.com/screen-share/element-capture/issues) and help make this a reality. (To ensure your feedback has the maximum impact, please mention the company/product this could help.)

**Comment by spxneo** [comment]
I can't believe it. I literally asked for this a few years ago and its finally here. amazing work!!!
